In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [17]:
#array is superclass in numpy and matrix is sub class of array

In [18]:
ar=np.array(l)

In [19]:
ar

array([1, 2, 3, 4])

In [20]:
type(ar)

numpy.ndarray

In [21]:
#nd means n dimansionalarray

In [22]:
np.array([[1,2],[4,5]])

array([[1, 2],
       [4, 5]])

In [23]:
np.asarray([1,2,3,4])

array([1, 2, 3, 4])

In [24]:
a=[2,3,4]

In [25]:
np.asanyarray(a)

array([2, 3, 4])

In [26]:
#wecan convert list into array by using array,as array,asanyarray

In [27]:
b=np.matrix(l)

In [28]:
b

matrix([[1, 2, 3, 4]])

In [29]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [30]:
c=np.array(l)

In [31]:
c

array([1, 2, 3, 4])

In [32]:
d=c

In [33]:
d

array([1, 2, 3, 4])

In [34]:
c

array([1, 2, 3, 4])

In [36]:
d[0]=100

In [37]:
d

array([100,   2,   3,   4])

In [38]:
c

array([100,   2,   3,   4])

In [39]:
e=np.copy(c)

In [40]:
e

array([100,   2,   3,   4])

In [41]:
c

array([100,   2,   3,   4])

In [42]:
c[1]=400

In [43]:
c

array([100, 400,   3,   4])

In [44]:
d

array([100, 400,   3,   4])

In [45]:
e

array([100,   2,   3,   4])

In [49]:
np.fromfunction(lambda i,j : i==j , (3,3))#work on matrix

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [50]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [52]:
iterable=(i*i for i in range(5))

In [54]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [56]:
np.fromstring("234 234",sep=" ")

array([234., 234.])

In [57]:
#numpy-datatypes

In [58]:
l=[1,2,3,4,5]

In [59]:
ar=np.array(l)

In [60]:
ar

array([1, 2, 3, 4, 5])

In [62]:
ar.ndim  #tell no of dimension in ar

1

In [63]:
ar2=np.array([[1,2,3,4],[5,6,7,8]])

In [64]:
ar2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
ar2.ndim

2

In [66]:
ar.size

5

In [69]:
ar.shape #it rep rows and colmuns

(5,)

In [70]:
ar2.shape

(2, 4)

In [71]:
ar2.dtype

dtype('int32')

In [75]:
ar22=np.array([(1.5,2,3,4,6),(45,57,9,68,71)])

In [76]:
ar22

array([[ 1.5,  2. ,  3. ,  4. ,  6. ],
       [45. , 57. ,  9. , 68. , 71. ]])

In [77]:
ar22.dtype

dtype('float64')

In [79]:
list(range(5))

[0, 1, 2, 3, 4]

In [80]:
#range take only int values

In [81]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [82]:
np.arange(3,4.5,.3)

array([3. , 3.3, 3.6, 3.9, 4.2])

In [83]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [84]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [85]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [86]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [87]:
np.ones(4)

array([1., 1., 1., 1.])

In [89]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [90]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [91]:
np.ones((2,3,4,2))

array([[[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]]])

In [92]:
on=np.ones((2,3))

In [93]:
on+5

array([[6., 6., 6.],
       [6., 6., 6.]])

In [94]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [96]:
np.eye(4)#identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [97]:
np.linspace(3,4,5)

array([3.  , 3.25, 3.5 , 3.75, 4.  ])

In [99]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [104]:
#imp functions

In [105]:
arr=np.random.randn(3,4)

In [106]:
import pandas as pd

In [107]:
pd.DataFrame(arr)

0         1         2         3
0  0.662122  0.878394 -1.433599  0.506033
1  1.630898  0.998728 -0.725343 -0.586783
2 -0.124482  0.128965  1.080870 -0.919537

In [114]:
arr4=np.random.rand(3,4)

In [115]:
np.random.randint(4,89,43)

array([81, 74, 65, 72, 76, 32, 87, 50, 65, 12, 31, 66, 32, 44, 15, 25, 39,
       69, 14, 80, 16, 78, 28, 42, 28, 83, 41, 41, 74, 44, 23,  9, 63, 88,
       13, 47, 18, 45, 87, 14,  7, 31,  4])

In [116]:
#we can also convert randoms into dataframe

In [118]:
arr4.reshape(6,2)

array([[0.53955695, 0.84253895],
       [0.14366486, 0.85194502],
       [0.61613009, 0.72413641],
       [0.17325253, 0.82756294],
       [0.0717317 , 0.41219248],
       [0.90822294, 0.4628906 ]])

In [120]:
arr3=arr4.reshape(6,-1345675)

In [121]:
arr3

array([[0.53955695, 0.84253895],
       [0.14366486, 0.85194502],
       [0.61613009, 0.72413641],
       [0.17325253, 0.82756294],
       [0.0717317 , 0.41219248],
       [0.90822294, 0.4628906 ]])

In [122]:
arr3[1]

array([0.14366486, 0.85194502])

In [123]:
arr3[1][1]

0.8519450207958638

In [124]:
arr3[2:5,1]

array([0.72413641, 0.82756294, 0.41219248])

In [127]:
arr5=np.random.randint(1,100,(5,4))

In [128]:
arr5

array([[48, 42, 80, 63],
       [55, 56,  5,  9],
       [73, 69,  9, 35],
       [72, 47, 35, 67],
       [16, 30, 85, 89]])

In [129]:
arr5>50

array([[False, False,  True,  True],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True, False, False,  True],
       [False, False,  True,  True]])

In [132]:
arr5[arr5>50]

array([80, 63, 55, 56, 73, 69, 72, 67, 85, 89])

In [133]:
arr5

array([[48, 42, 80, 63],
       [55, 56,  5,  9],
       [73, 69,  9, 35],
       [72, 47, 35, 67],
       [16, 30, 85, 89]])

In [136]:
arr5[2:4,[1,3]]

array([[69, 35],
       [47, 67]])

In [138]:
arr5[0][0]=600

In [139]:
arr5

array([[600,  42,  80,  63],
       [ 55,  56,   5,   9],
       [ 73,  69,   9,  35],
       [ 72,  47,  35,  67],
       [ 16,  30,  85,  89]])

In [141]:
arr6=np.random.randint(1,3,(3,3))
arr7=np.random.randint(1,3,(3,3))

In [142]:
arr6

array([[1, 2, 1],
       [1, 1, 2],
       [2, 1, 2]])

In [143]:
arr7

array([[2, 2, 1],
       [2, 2, 1],
       [1, 2, 1]])

In [144]:
arr6+arr7

array([[3, 4, 2],
       [3, 3, 3],
       [3, 3, 3]])

In [147]:
arr6*arr7 #it multiply by index only

array([[2, 4, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [148]:
arr6@arr7  #matrix multiplication

array([[ 7,  8,  4],
       [ 6,  8,  4],
       [ 8, 10,  5]])

In [150]:
arr6/0

C:\Users\Hp\AppData\Local\Temp\ipykernel_6140\1351048935.py:1: RuntimeWarning: divide by zero encountered in divide
  arr6/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [151]:
arr6+100

array([[101, 102, 101],
       [101, 101, 102],
       [102, 101, 102]])

In [152]:
arr6**2

array([[1, 4, 1],
       [1, 1, 4],
       [4, 1, 4]])

In [154]:
#numpy--broadcasting

In [156]:
arr8=np.zeros((4,4))

In [157]:
arr8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [158]:
row=np.array([1,2,3,4])

In [159]:
row

array([1, 2, 3, 4])

In [160]:
arr8+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [161]:
row.ndim

1

In [162]:
row.T

array([1, 2, 3, 4])

In [163]:
np.exp(arr6)

array([[2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 7.3890561 ]])

In [164]:
np.log10(arr6)

array([[0.     , 0.30103, 0.     ],
       [0.     , 0.     , 0.30103],
       [0.30103, 0.     , 0.30103]])

# part2

In [1]:
#numpy-array manipulation

In [2]:
import numpy as np

In [3]:
arr=np.random.randint(1,10,(3,4))

In [4]:
arr

array([[7, 5, 3, 7],
       [9, 8, 2, 7],
       [3, 8, 1, 1]])

In [5]:
arr.reshape(6,2)

array([[7, 5],
       [3, 7],
       [9, 8],
       [2, 7],
       [3, 8],
       [1, 1]])

In [6]:
arr.reshape(3,-76543)

array([[7, 5, 3, 7],
       [9, 8, 2, 7],
       [3, 8, 1, 1]])

In [7]:
arr.T

array([[7, 9, 3],
       [5, 8, 8],
       [3, 2, 1],
       [7, 7, 1]])

In [9]:
arr.flatten()#convert into 1d

array([7, 5, 3, 7, 9, 8, 2, 7, 3, 8, 1, 1])

In [11]:
arr1=np.array([1,2,3,3,4])

In [12]:
arr1.ndim

1

In [13]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [14]:
arr

array([[7, 5, 3, 7],
       [9, 8, 2, 7],
       [3, 8, 1, 1]])

In [15]:
np.squeeze(arr)

array([[7, 5, 3, 7],
       [9, 8, 2, 7],
       [3, 8, 1, 1]])

In [16]:
data=np.array([[1],[2],[3]])

In [17]:
data

array([[1],
       [2],
       [3]])

In [18]:
np.squeeze(data)

array([1, 2, 3])

In [19]:
arr1

array([1, 2, 3, 3, 4])

In [20]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [22]:
np.roll(arr1, 2)

array([3, 4, 1, 2, 3])

In [23]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [26]:
#numpy-binary operation include simple add etc

In [28]:
#sort,search and counting functions

In [30]:
arr4=np.array([4,3,2,6,5,7,89,55,7,3,5,0])

In [31]:
arr4

array([ 4,  3,  2,  6,  5,  7, 89, 55,  7,  3,  5,  0])

In [33]:
np.sort(arr4)

array([ 0,  2,  3,  3,  4,  5,  5,  6,  7,  7, 55, 89])

In [34]:
np.searchsorted(arr4,89)

6

In [35]:
arr5=np.array([0,4,10,50,6,34,5,6])

In [36]:
np.count_nonzero(arr5)

7

In [37]:
arr4

array([ 4,  3,  2,  6,  5,  7, 89, 55,  7,  3,  5,  0])

In [38]:
np.where(arr4>6)

(array([5, 6, 7, 8], dtype=int64),)

In [39]:
np.extract(arr5>5,arr5)

array([10, 50,  6, 34,  6])

In [40]:
#copy and views

In [45]:
arr6=([4,5,6,7,8,9,0,2,3,4,5,55])

In [46]:
arr6

[4, 5, 6, 7, 8, 9, 0, 2, 3, 4, 5, 55]

In [47]:
a=np.copy(arr6)

In [51]:
b = arr6.view()

AttributeError: 'list' object has no attribute 'view'

In [52]:
#matrix library

In [53]:
import numpy.matlib as nm

In [54]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [55]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [56]:
nm.eye(7)

matrix([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.]])

In [57]:
#linear algebra

In [58]:
arr1=np.random.randint([[2,3],[4,5]])

In [59]:
arr2=np.random.randint([[5,3],[2,5]])

In [60]:
np.dot(arr1,arr2)

array([[0, 0],
       [1, 6]])

In [61]:
arr1@arr2

array([[0, 0],
       [1, 6]])